# Consistency Modes
MODE_STRONG = "STRONG"
MODE_EVENTUAL = "EVENTUAL"

# Default Values
DEFAULT_USER = "anonymous"
DEFAULT_TIMESTAMP = 0
DEFAULT_NODE_ID = "unknown"
DEFAULT_PORT = 5000

# Network Configuration
HTTP_PROTOCOL_PREFIX = "http"
REQUEST_TIMEOUT_SECONDS = 2

# Gossip Configuration
GOSSIP_INTERVAL_MIN_SECONDS = 2
GOSSIP_INTERVAL_MAX_SECONDS = 5

# Quorum Configuration
COORDINATOR_INITIAL_VOTE = 1

# HTTP Status Codes
HTTP_OK = 200
HTTP_ACCEPTED = 202
HTTP_BAD_REQUEST = 400
HTTP_INTERNAL_SERVER_ERROR = 500
